# Generated by Django 5.1.4 on 2025-01-08 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
                'ordering': ['socio'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField(verbose_name='Duración (meses)')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=50, null=True)),
                ('comprobante_nro', models.CharField(blank=True, max_length=50, null=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.membresia')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['membresia', '-fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='membresia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.plan'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gym.socio'),
        ),
    ]
