# Generated by Django 5.1.4 on 2025-01-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPago',
        ),
    ]
