# Generated by Django 5.1.4 on 2024-12-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gym.socio'),
        ),
    ]
