# Generated by Django 5.1.4 on 2025-01-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_membresia_estado_alter_membresia_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='asistencia',
        ),
    ]
