# Generated by Django 5.1.4 on 2025-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_membresia_socio_alter_pago_estado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('socio', 'plan'), name='unique_socio_plan'),
        ),
    ]
