# Generated by Django 5.1.4 on 2025-01-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_historicalmembresia_historicalpago_historicalplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpago',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
    ]
