# Generated by Django 5.1.4 on 2025-01-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_historicalpago_borrado_pago_borrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpago',
            name='borrado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='borrado',
        ),
    ]
